@startuml
autonumber
skinparam style strictuml

actor "Visitante" as Guest
boundary "Frontend" as UI

box "Backend" #f9f9f9
    control "auth_controller" as Ctrl <<control>>
    control "auth_service" as Serv <<service>>
    collections "user_repository" as Repo <<repository>>
end box

box "Infra" #e8f4f8
    database "PostgreSQL (DB)" as DB
end box

== Fluxo: Fazer Login ==

Guest -> UI++: Preenche dados (email, password)
UI -> Ctrl++: POST /auth/login (email, password)
Ctrl -> Ctrl++--: Valida entrada (LoginSchema)

alt Dados inválidos ou incompletos
    note right of Ctrl #f8d7da: **raise** ValidationError
end

Ctrl -> Serv++: login(data)
Serv -> Repo++: get_user(email)
Repo -> DB++: Obtém User (email)
DB --> Repo--: User / Null
Repo --> Serv--: User / Null

alt Usuário não encontrado
    note right of Serv #f8d7da: **raise** UnauthorizedError
end

Serv -> Serv++--: check_password(User, password)

alt Credenciais Inválidas
    note right of Serv #f8d7da: **raise** UnauthorizedError
end

Serv -> Serv++--: check_status_policy(User)

alt Conta banida
    note right of Serv #f8d7da: **raise** ForbiddenError
end

alt Conta inativa
    note right of Serv #f8d7da: **raise** ConflictError
    note right of Serv #fff3cd: **Ponto de extensão:**\nSolicitação de Reativação
end

Serv -> Serv++--: generate_token(user)
Serv --> Ctrl-- : token, User
Ctrl -> Ctrl++--: Aplica AuthResponseSchema (token, User)
Ctrl --> UI--: AuthResponse
note right of UI #d4edda: **Status:** 200 OK
UI --> Guest--: Login realizado
@enduml