@startuml
autonumber
skinparam style strictuml

actor "Usuário/Visitante" as User
participant "Frontend" as UI

box "Backend" #f9f9f9
    participant "Camada de Interface" as CI
    participant "Camada de Negócio" as CN
    participant "Camada de Dados" as CD
end box

box "Infra" #e8f4f8
    participant "PostgreSQL (DB)" as DB
end box

== Fluxo: Visualizar Feed ==

User -> UI : Acessa feed
opt Utiliza filtros
    User -> UI : Define filtros
end
activate UI
UI -> CI : GET /posts?params
activate CI
CI -> CI : Valida Entrada (FeedRequestSchema)
activate CI
deactivate CI

alt Parâmetros inválidos ou incompletos
    CI --> UI : 400 Bad Request
    UI --> User : Exibe alertas nos filtros
else Parâmetros Ok
    CI -> CN : Buscar Posts (params)
    activate CN
    CN -> CN : Aplica valores padrão se necessário (params)
    activate CN
    deactivate CN
    CN -> CD : Buscar postagens públicas paginadas (params)
    activate CD
    note right of CD
    Monta consulta dinâmica
    utilizando filtros,
    paginação e regras
    de visibilidade
    end note
    CD -> DB : Consulta postagens (params)
    activate DB
    DB --> CD : Posts
    deactivate DB
    CD --> CN : Posts
    deactivate CD
    CN --> CI : Posts
    deactivate CN
    CI -> CI : Aplica PostResponseSchema (Posts)
    activate CI
    deactivate CI
    CI --> UI : 200 OK (0..* PostResponse)
    deactivate CI
    UI --> User : Exibe cards no Feed
    deactivate UI
end
@enduml