@startuml
autonumber
skinparam style strictuml

actor "Usuário" as User
boundary "Frontend" as UI

box "Backend" #f9f9f9
    control "Controller" as Ctrl <<control>>
    control "Service" as Serv <<service>>
    collections "Repository" as Repo <<repository>>
end box

box "Infra" #e8f4f8
    database "PostgreSQL (DB)" as DB
end box

== Fluxo: Alterar Minha Senha ==

User -> UI++: Clica em "Alterar Minha Senha"
UI -> UI++--: Solicita senha atual e a nova
User -> UI: Preenche dados\n(old_password, new_password)
UI -> Ctrl++: PATCH /me/password (token,\nold_password, new_password)
Ctrl -> Ctrl++--: Valida entrada (PasswordUpdateSchema)

alt Dados inválidos ou incompletos
    note right of Ctrl #f8d7da: **raise** ValidationError
end

group ref
    note right of Ctrl #fff3cd: **Fluxo:** Autenticação e Autorização
end

Ctrl -> Serv++: Atualizar senha\n(User, old_password, new_password)
Serv -> Serv++--: Verifica senha atual

alt Senha incorreta
    note right of Serv #f8d7da: **raise** UnauthorizedError
end

Serv -> Serv++--: Gera hash da senha (new_password)
Serv -> Repo++: Editar User (user_id, password=hash)
Repo -> DB++: Atualiza User (user_id, data)
DB --> Repo--: Sucesso
Repo --> Serv--: Sucesso
Serv --> Ctrl--: Sucesso
Ctrl --> UI--: Sucesso
note right of UI #d4edda: **Status:** 204 No Content
UI --> User--: Exibe mensagem de confirmação
@enduml