@startuml
autonumber
skinparam style strictuml

actor "Usuário" as User
boundary "Frontend" as UI

box "Backend" #f9f9f9
    control "Controller" as Ctrl <<control>>
    control "Service" as Serv <<service>>
    collections "Repository" as Repo <<repository>>
end box

box "Infra" #e8f4f8
    database "PostgreSQL (DB)" as DB
end box

== Fluxo: Fazer uma Postagem ==

User -> UI++: Preenche dados (data)
UI -> Ctrl++: POST /me/posts (token, data)
Ctrl -> Ctrl++--: Valida entrada (PostCreateSchema)

alt Dados inválidos ou incompletos
    note right of Ctrl #f8d7da: **raise** ValidationError
end

group ref
    note right of Ctrl #fff3cd: **Fluxo:** Autenticação e Autorização
end

Ctrl -> Serv++: Criar Post (user_id, data)
Serv -> Repo++: Salvar Post (user_id, data,\nstatus=active)
Repo -> DB++: Cria Post (user_id, data)
DB --> Repo--: Post
Repo --> Serv--: Post
Serv --> Ctrl--: Post
Ctrl -> Ctrl++--: Aplica PostResponseSchema (Post)
Ctrl --> UI--: PostResponse
note right of UI #d4edda: **Status:** 201 Created
UI -> UI++--: Oferece a opção de\nupload de imagens
note right of UI #fff3cd: **Ponto de extensão:**\nUpload de Imagens
UI --> User--: Postagem criada
@enduml