"""add filename to images

Revision ID: bf7c8bbc2d39
Revises: d969e1f96174
Create Date: 2026-05-07 13:58:11.002997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf7c8bbc2d39'
down_revision: Union[str, Sequence[str], None] = 'd969e1f96174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('filename', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'filename')
    # ### end Alembic commands ###
