"""fix: nomes dos campos das tabelas em ingles, de acordo com o design system

Revision ID: d969e1f96174
Revises: 357172c03c3c
Create Date: 2026-04-19 20:40:37.547233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd969e1f96174'
down_revision: Union[str, Sequence[str], None] = '357172c03c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pets', 'nome', new_column_name='name')
    op.alter_column('pets', 'tipo', new_column_name='type')
    op.alter_column('pets', 'data', new_column_name='date')
    op.alter_column('pets', 'descricao', new_column_name='description')

    op.alter_column('users', 'nome', new_column_name='name')
    op.alter_column('users', 'senha', new_column_name='password')
    op.alter_column('users', 'telefone', new_column_name='contact')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pets', 'name', new_column_name='nome')
    op.alter_column('pets', 'type', new_column_name='tipo')
    op.alter_column('pets', 'date', new_column_name='data')
    op.alter_column('pets', 'description', new_column_name='descricao')

    op.alter_column('users', 'name', new_column_name='nome')
    op.alter_column('users', 'password', new_column_name='senha')
    op.alter_column('users', 'contact', new_column_name='telefone')
    # ### end Alembic commands ###
