@startuml
left to right direction
skinparam packageStyle rectangle
skinparam shadowing false


actor "Visitante" as Guest
actor "Usuário Autenticado" as User
actor "Administrador" as Admin

rectangle "Sistema de Busca de Pets: OndeTa?" {
  package "Acesso" {
    usecase "Cadastrar Usuário" as UC1
    usecase "Fazer Login" as UC2
  }
  package "Funcionalidades Principais" {
    usecase "Visualizar Feed" as UC3
    usecase "Filtrar Resultados" as UC3_EXT
    usecase "Visualizar Mapa" as UC4
    usecase "Destacar Pet no Mapa" as UC4_SPEC
    usecase "Publicar Post" as UC5
  }
  package "Painel do Usuário" {
    usecase "Gerenciar Minha Conta" as UC_ACC
    usecase "Editar Meu Perfil" as UC_ACC_EDIT
    usecase "Excluir Minha Conta" as UC_ACC_DEL

    usecase "Ver Meus Posts" as UC_POST
    usecase "Editar Meu Post" as UC_POST_EDIT
    usecase "Excluir Meu Post" as UC_POST_DEL
    usecase "Adicionar/Remover Imagens" as UC_POST_IMG
  }
  package "Moderação" {
    usecase "Moderar Conteúdo" as UC_MOD
    usecase "Editar Post Impróprio" as UC_MOD_EDIT
    usecase "Banir Usuário" as UC_MOD_BAN
    usecase "Remover Imagens Impróprias" as UC_MOD_IMG
  }
}

' Relacionamentos do Visitante
Guest --> UC1
Guest --> UC2
UC1 .r.> UC2 : <<include>>
Guest --> UC3
UC3 <.. UC3_EXT : <<extend>>
Guest --> UC4
UC4 <.. UC4_SPEC : <<extend>>


' Relacionamentos do Usuário Autenticado
User --|> Guest
User --> UC5

User --> UC_ACC
UC_ACC <|-- UC_ACC_EDIT
UC_ACC <|-- UC_ACC_DEL

User --> UC_POST
UC_POST <|-- UC_POST_EDIT
UC_POST_EDIT <.r. UC_POST_IMG : <<extend>>
UC_POST <|-- UC_POST_DEL

' Relacionamentos do  Admin
Admin --|> User
Admin --> UC_MOD

UC_MOD <|-- UC_MOD_EDIT
UC_MOD_EDIT <.l. UC_MOD_IMG : <<extend>>
UC_MOD <|-- UC_MOD_BAN

@enduml