@startuml
autonumber
skinparam style strictuml
skinparam MaxMessageSize 200

actor "Usuário" as User
participant "Frontend" as UI

box "Backend" #f9f9f9
    participant "Camada de Interface" as CI
    participant "Camada de Negócio" as CN
    participant "Camada de Dados" as CD
end box

box "Infra" #e8f4f8
    participant "Storage" as Cloud
    participant "PostgreSQL (DB)" as DB
end box

== Início do Fluxo ==

User -> UI : Preenche dados e envia fotos
activate UI
UI -> CI : POST /posts (data, files)
activate CI
CI -> CI : Identifica o usuário (user_id)
CI -> CI : Valida Entrada (PostCreateSchema)

alt Dados Inválidos
    CI --> UI : 400 Bad Request
    UI --> User : Exibe alertas nos campos
else Dados Ok
    CI -> CN : Cria post (user_id, data, files)
    activate CN

    == Persistência Inicial ==

    CN -> CD : Novo registro (user_id, data, status='pending')
    activate CD
    CD -> DB : INSERT INTO posts
    activate DB
    DB --> CD : post_id
    deactivate DB
    CD --> CN : post_id
    deactivate CD

    == Processamento de Imagens ==

    CN -> CN : has_images = False

    loop para cada imagem em files
        CN -> Cloud : Upload de imagem
        activate Cloud
        alt Falha no Upload
            Cloud --> CN : Erro (continua loop)
        else Upload realizado
            Cloud --> CN : url_img
            deactivate Cloud
            CN -> CD : Registro de imagem (post_id, url_img)
            activate CD
            CD -> DB : INSERT INTO images
            activate DB

            alt Falha no Registro
                DB --> CD : Erro
                CD --> CN : Erro
                CN -> Cloud : Deleta imagem com url_img
                activate Cloud
                Cloud --> CN : Sucesso
                deactivate Cloud
            else Registro realizado
                DB --> CD : Sucesso
                deactivate DB
                CD --> CN : Sucesso
                deactivate CD
                CN -> CN : has_images = True
            end
        end
    end

    == Finalização de Fluxo ==

    alt has_images == False
        CN --> CI : Post status: "pending"
        CI --> UI : 201 Created
        UI --> User : "Dados salvos, mas houve erro nas fotos.\nComplete no seu Perfil."
    else has_images == True
        CN -> CD : Atualiza status (post_id, 'active')
        activate CD
        CD -> DB : UPDATE posts SET status='active'
        activate DB
        DB --> CD : Sucesso
        deactivate DB
        CD --> CN : Sucesso
        deactivate CD
        CN --> CI : Post status: "active"
        deactivate CN
        CI --> UI : 201 Created
        deactivate CI
        UI --> User : "Post publicado com sucesso!"
        deactivate UI
    end
end
@enduml